# Change these first
owner: TeamHavit # Your GitHub organization or username, where this repository lives
repo: Havit-Server-Upptime # The name of this repository

sites:
  - name: Havit Push Server - DEV
    url: $SECRET_SITE
    method: GET
    expectedStatusCodes:
      - 200
#  - name: Havit Push Server - PROD
 #   url: $SECRET_SITE_1
 #   method: GET
 #   expectedStatusCodes:
 #     - 200 
    
assignees: # Users to assign downtime issues (optional)
  - jokj624
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /Havit-Server-Upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Havit Server Health Check
  introTitle: "Havit Server"
  introMessage: HAVIT 서버의 구동 상태를 확인합니다.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/TeamHavit

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
